import React, { useState } from 'react';
import { PREBUILT_TOOLS } from '../utils/sampleData';
import { Copy, Check, Terminal, Sparkles } from 'lucide-react';

export const CodeGenerator: React.FC = () => {
  const [provider, setProvider] = useState<'openai' | 'anthropic'>('openai');
  const [selectedToolId, setSelectedToolId] = useState<string>('get_weather');
  const [copied, setCopied] = useState(false);

  const activeTool = PREBUILT_TOOLS.find(t => t.id === selectedToolId) || PREBUILT_TOOLS[0];

  const generatePythonOpenAI = () => {
    return `import json
from openai import OpenAI

client = OpenAI()

# 1. Define Tool Schema according to OpenAI Specification
tools = [
    ${JSON.stringify(activeTool.openaiSchema, null, 8).replace(/\n/g, '\n    ')}
]

# 2. Local Python Function Implementation
def ${activeTool.name}(**kwargs):
    print(f"Executing ${activeTool.name} locally with args:", kwargs)
    return ${JSON.stringify(activeTool.mockHandler({ location: 'Tokyo' }), null, 4)}

# 3. Initial Chat Completion Request
messages = [{"role": "user", "content": "Fetch weather for Tokyo"}]

response = client.chat.completions.create(
    model="gpt-4o",
    messages=messages,
    tools=tools,
    tool_choice="auto"
)

response_message = response.choices[0].message

# 4. Handle Tool Calls if generated by LLM
if response_message.tool_calls:
    messages.append(response_message)  # Append assistant tool call request
    
    for tool_call in response_message.tool_calls:
        function_name = tool_call.function.name
        function_args = json.loads(tool_call.function.arguments)
        
        if function_name == "${activeTool.name}":
            result = ${activeTool.name}(**function_args)
            
            # Append tool result with role="tool"
            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": json.dumps(result)
            })

    # 5. Final Synthesis Call
    final_response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages
    )
    print("Final Answer:", final_response.choices[0].message.content)
`;
  };

  const generatePythonAnthropic = () => {
    return `import json
import anthropic

client = anthropic.Anthropic()

# 1. Define Tool Schema according to Anthropic Specification
tools = [
    ${JSON.stringify(activeTool.anthropicSchema, null, 8).replace(/\n/g, '\n    ')}
]

# 2. Local Python Function Implementation
def ${activeTool.name}(**kwargs):
    print(f"Executing ${activeTool.name} locally with args:", kwargs)
    return ${JSON.stringify(activeTool.mockHandler({ location: 'Tokyo' }), null, 4)}

# 3. Initial Request
messages = [{"role": "user", "content": "Fetch weather for Tokyo"}]

response = client.messages.create(
    model="claude-3-5-sonnet-20241022",
    max_tokens=1024,
    tools=tools,
    messages=messages
)

# 4. Process Tool Use Content Blocks
if response.stop_reason == "tool_use":
    # Append assistant's response to conversation history
    messages.append({"role": "assistant", "content": response.content})
    
    tool_result_blocks = []
    for block in response.content:
        if block.type == "tool_use":
            tool_use_id = block.id
            tool_name = block.name
            tool_input = block.input
            
            if tool_name == "${activeTool.name}":
                result = ${activeTool.name}(**tool_input)
                
                tool_result_blocks.append({
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": json.dumps(result),
                    "is_error": False
                })

    # Append user role message containing tool_result blocks
    messages.append({
        "role": "user",
        "content": tool_result_blocks
    })
    
    # 5. Final Synthesis Call
    final_response = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=1024,
        tools=tools,
        messages=messages
    )
    print("Final Answer:", final_response.content[0].text)
`;
  };

  const getSnippet = () => {
    if (provider === 'openai') {
      return generatePythonOpenAI();
    } else {
      return generatePythonAnthropic();
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getSnippet());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8">
      
      {/* Header Panel */}
      <div className="glass-card p-6 md:p-8 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 pb-6 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-2 rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                <Sparkles className="w-5 h-5" />
              </span>
              <h2 className="text-xl font-bold text-slate-100 tracking-tight">
                Production SDK Code Generator
              </h2>
            </div>
            <p className="text-xs text-slate-400 mt-1 max-w-2xl">
              Generate fully functional, copy-paste ready Python code for complete multi-turn tool loops with full error handling and result formatting.
            </p>
          </div>

          <div className="flex items-center gap-3">
            {/* Provider Selector */}
            <div className="flex items-center gap-1.5 bg-slate-950 p-1.5 rounded-xl border border-slate-800 shadow-inner">
              <button
                onClick={() => setProvider('openai')}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                  provider === 'openai'
                    ? 'bg-emerald-600 text-white shadow-md shadow-emerald-600/30'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                OpenAI SDK
              </button>
              <button
                onClick={() => setProvider('anthropic')}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                  provider === 'anthropic'
                    ? 'bg-amber-600 text-white shadow-md shadow-amber-600/30'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Anthropic SDK
              </button>
            </div>
          </div>
        </div>

        {/* Tool Target Selector */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Select Tool Target:</span>
            {PREBUILT_TOOLS.map((t) => (
              <button
                key={t.id}
                onClick={() => setSelectedToolId(t.id)}
                className={`text-xs px-3 py-1.5 rounded-lg border font-mono transition-all ${
                  selectedToolId === t.id
                    ? 'bg-indigo-600 border-indigo-500 text-white font-semibold shadow-md shadow-indigo-600/30'
                    : 'bg-slate-900 border-slate-800 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                {t.name}
              </button>
            ))}
          </div>

          <button
            onClick={handleCopy}
            className="py-2.5 px-5 rounded-xl bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-600 hover:from-indigo-400 hover:to-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/25 transition-all flex items-center justify-center gap-2 cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Python SDK Code'}</span>
          </button>
        </div>
      </div>

      {/* Code Snippet Box */}
      <div className="glass-card p-6 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <span className="text-xs font-mono text-slate-300 font-semibold flex items-center gap-2">
            <Terminal className="w-4 h-4 text-indigo-400" />
            main.py ({provider.toUpperCase()} Multi-Turn Loop)
          </span>
          <span className="text-[11px] text-slate-400 font-mono">
            {provider === 'openai' ? 'pip install openai' : 'pip install anthropic'}
          </span>
        </div>

        <div className="bg-slate-950 p-5 rounded-xl border border-slate-800 overflow-x-auto max-h-[600px]">
          <pre className="text-xs text-indigo-200 font-mono leading-relaxed">
            {getSnippet()}
          </pre>
        </div>
      </div>
    </div>
  );
};
