import React, { useState } from 'react';
import { PREBUILT_TOOLS } from '../utils/sampleData';
import { Code2, Copy, Check, Terminal } from 'lucide-react';

export const CodeGenerator: React.FC = () => {
  const [provider, setProvider] = useState<'openai' | 'anthropic'>('openai');
  const [selectedToolId, setSelectedToolId] = useState<string>('get_weather');
  const [copied, setCopied] = useState(false);

  const activeTool = PREBUILT_TOOLS.find(t => t.id === selectedToolId) || PREBUILT_TOOLS[0];

  const generatePythonOpenAI = () => {
    return `import json
from openai import OpenAI

client = OpenAI()

# 1. Define Tool Schema according to OpenAI Specification
tools = [
    ${JSON.stringify(activeTool.openaiSchema, null, 8).replace(/\n/g, '\n    ')}
]

# 2. Local Python Function Implementation
def ${activeTool.name}(**kwargs):
    print(f"Executing ${activeTool.name} locally with args:", kwargs)
    return ${JSON.stringify(activeTool.mockHandler({ location: 'Tokyo' }), null, 4)}

# 3. Initial Chat Completion Request
messages = [{"role": "user", "content": "Fetch weather for Tokyo"}]

response = client.chat.completions.create(
    model="gpt-4o",
    messages=messages,
    tools=tools,
    tool_choice="auto"
)

response_message = response.choices[0].message

# 4. Handle Tool Calls if generated by LLM
if response_message.tool_calls:
    messages.append(response_message)  # Append assistant tool call request
    
    for tool_call in response_message.tool_calls:
        function_name = tool_call.function.name
        function_args = json.loads(tool_call.function.arguments)
        
        if function_name == "${activeTool.name}":
            result = ${activeTool.name}(**function_args)
            
            # Append tool result with role="tool"
            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": json.dumps(result)
            })

    # 5. Final Synthesis Call
    final_response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages
    )
    print("Final Answer:", final_response.choices[0].message.content)
`;
  };

  const generatePythonAnthropic = () => {
    return `import json
import anthropic

client = anthropic.Anthropic()

# 1. Define Tool Schema according to Anthropic Specification
tools = [
    ${JSON.stringify(activeTool.anthropicSchema, null, 8).replace(/\n/g, '\n    ')}
]

# 2. Local Python Function Implementation
def ${activeTool.name}(**kwargs):
    print(f"Executing ${activeTool.name} locally with args:", kwargs)
    return ${JSON.stringify(activeTool.mockHandler({ location: 'Tokyo' }), null, 4)}

# 3. Initial Request
messages = [{"role": "user", "content": "Fetch weather for Tokyo"}]

response = client.messages.create(
    model="claude-3-5-sonnet-20241022",
    max_tokens=1024,
    tools=tools,
    messages=messages
)

# 4. Process Tool Use Content Blocks
if response.stop_reason == "tool_use":
    # Append assistant's response to conversation history
    messages.append({"role": "assistant", "content": response.content})
    
    tool_result_blocks = []
    for block in response.content:
        if block.type == "tool_use":
            tool_use_id = block.id
            tool_name = block.name
            tool_input = block.input
            
            if tool_name == "${activeTool.name}":
                result = ${activeTool.name}(**tool_input)
                
                tool_result_blocks.append({
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": json.dumps(result),
                    "is_error": False
                })

    # Append user role message containing tool_result blocks
    messages.append({
        "role": "user",
        "content": tool_result_blocks
    })
    
    # 5. Final Synthesis Call
    final_response = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=1024,
        tools=tools,
        messages=messages
    )
    print("Final Answer:", final_response.content[0].text)
`;
  };

  const getSnippet = () => {
    if (provider === 'openai') {
      return generatePythonOpenAI();
    } else {
      return generatePythonAnthropic();
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getSnippet());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="glass-panel p-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-white/10">
          <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Code2 className="w-5 h-5 text-indigo-400" />
              Production SDK Code Generator
            </h2>
            <p className="text-sm text-gray-400 mt-1">
              Generate fully functional, copy-paste ready Python code for complete multi-turn tool loops.
            </p>
          </div>

          <div className="flex items-center gap-3">
            {/* Provider Selector */}
            <div className="flex items-center gap-1 bg-black/40 p-1 rounded-xl border border-white/10">
              <button
                onClick={() => setProvider('openai')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${
                  provider === 'openai' ? 'bg-emerald-600 text-white' : 'text-gray-400 hover:text-white'
                }`}
              >
                OpenAI SDK
              </button>
              <button
                onClick={() => setProvider('anthropic')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${
                  provider === 'anthropic' ? 'bg-amber-600 text-white' : 'text-gray-400 hover:text-white'
                }`}
              >
                Anthropic SDK
              </button>
            </div>
          </div>
        </div>

        {/* Select Tool Target */}
        <div className="flex items-center justify-between pt-6">
          <div className="flex items-center gap-2">
            <span className="text-xs text-gray-400 font-medium">Select Registered Tool:</span>
            {PREBUILT_TOOLS.map((t) => (
              <button
                key={t.id}
                onClick={() => setSelectedToolId(t.id)}
                className={`text-xs px-3 py-1.5 rounded-lg border font-mono transition-all ${
                  selectedToolId === t.id
                    ? 'bg-indigo-600 border-indigo-500 text-white font-semibold'
                    : 'bg-white/5 border-white/10 text-gray-300 hover:bg-white/10'
                }`}
              >
                {t.name}
              </button>
            ))}
          </div>

          <button
            onClick={handleCopy}
            className="btn-primary text-xs py-2 px-4"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Python Code'}
          </button>
        </div>
      </div>

      {/* Code Snippet Box */}
      <div className="glass-panel p-5 space-y-3">
        <div className="flex items-center justify-between border-b border-white/10 pb-3">
          <span className="text-xs font-mono text-gray-400 flex items-center gap-2">
            <Terminal className="w-4 h-4 text-indigo-400" />
            main.py ({provider.toUpperCase()} Multi-Turn Loop)
          </span>
          <span className="text-[11px] text-gray-500 font-mono">
            {provider === 'openai' ? 'openai>=1.0.0' : 'anthropic>=0.18.0'}
          </span>
        </div>

        <div className="bg-slate-950 p-4 rounded-xl border border-white/10 overflow-x-auto max-h-[600px]">
          <pre className="text-xs text-indigo-200 font-mono leading-relaxed">
            {getSnippet()}
          </pre>
        </div>
      </div>
    </div>
  );
};
